dubbing.flat.ratePerUnit=2.34

translation..flat.ratePerUnit=3.12
translation.subscription.fixPrice=2
translation.subscription.fixAllowedQuantity=3
translation.subscription.perUnitRate=4

transcription.flat.ratePerUnit=4.02

transcription.subscription.fixPrice=2.16
transcription.subscription.fixAllowedQuantity=3.18
transcription.subscription.perUnitRate=4

transcription.tier.amounts=10,8,5
transcription.tier.prices=10,5,2